[doc]
config = {tag_mode = "open"}
"!doctype html" = ""

[doc.html]
config = {tag_mode = "pair"}
attrib = {lang = "en"}

[doc.html.head]
title = "{metadata[title]}"

[[doc.html.head.meta]]
config = {tag_mode = "open"}
attrib = {charset = "UTF-8"}

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {name = "viewport", content = "width=device-width, initial-scale=1.0"}

[[doc.html.head.meta]]
config = {tag_mode = "open"}
attrib = {http-equiv = "X-UA-Compatible", content = "ie=edge"}

[[doc.html.body.main.section]]
code = """
<html>
<head></head>
<body>
...
"""

[[doc.html.body.main.section]]
attrib = {"class" = "pulse"}
code = """
<p>Hello, World!</p>
"""

[[doc.html.body.main.section]]
code = """
...
</body>
</html>
"""
