[metadata]
title = "Five Whys"

[doc]
config = {tag_mode = "open"}
"!doctype html" = ""

[doc.html.body.main]
blocks = [
"""
<A> I want to get to the bottom of this.
    So I thought we'd trying doing the 'Five Whys'.
    Do you know it?
<B> Thats like, you ask 'Why' five times and then
    discover the hidden cause of something?
<A> Yes, it's for root cause analysis.
<B> Yeah, I know the kind of thing.
""",
"""
<A> So, why are we doing this today then?
<B> Well it's for practice really.
""",
"""
<A> Why do you need to practice?
<B> I'm very new to making videos. I don't know what I'm doing.
""",
"""
<A> And why are you making a video?
<B> It's for YouTube.
""",
"""
<A> And why do you want to be on YouTube?
<B> It's not like I actually *want* to be on YouTube.
<A> Hmmm.
<B> Not everyone around me wants to hear what I have to say all the time.
<A> Yes, I guess not everybody's cup of tea. All the... You know.
<B> So maybe it's about finding some people who do.
""",
"""
<A> So why do you feel the need so much to...?
<B> Articulate my ideas?
<A> Yeah. A lot of people are wondering actually.
<B> There are some topics I've been thinking about, that I'm pretty sure very few
    other people can be bothered to think about. Maybe a handful.
<A> That many?
<B> Maybe. I just think it would be a shame if that was to disappear

""",
]
