[metadata]
title = "Five Whys"

[doc]
config = {tag_mode = "open"}
"!doctype html" = ""

[doc.html.body.main]
blocks = [
"""
<A> I want to get to the bottom of this.
    So I thought we'd try doing the 'Five Whys'.
    Do you know it?
<B> Thats like, you ask 'Why' five times and then
    discover the hidden reason for something?
<A> Yes, it's a method of root cause analysis.
<B> Yeah, I know the kind of thing.
""",
"""
<A> So, why are we doing this today then?
<B> Well it's for practice really.
""",
"""
<A> Why do you need to practice?
<B> I'm very new to making videos. I don't know what I'm doing.
""",
"""
<A> And why are you making a video?
<B> It's for YouTube.
""",
"""
<A> And why do you want to be on YouTube?
<B> It's not like I actually *want* to be on YouTube.
<A> Hmmm.
<B> But there's a limit to the number of people I know personally who really
    want to hear what I have to say all the time.
<A> Yes, I guess you're not everybody's cup of tea. All the... You know.
<B> So maybe it's about finding some others who do.
<A> Yes, yes.
""",
"""
<A> Why is it do you think, you feel the need so much to...?
<B> Articulate my ideas?
<A> Yes. A lot of people are wondering that actually.
<B> If you have a packet of biscuits you should pass them round, shouldn't you?
    And if you don't want a biscuit don't take one.
<A> Is it the same thing though?
""",
"""
<B> What's with the pipe anyway?
<A> Mate, I'm supposed to be asking the questions.
<B> No, you were doing the Whys. We've had those.
    I'm asking, *what* are you smoking a pipe for?
<A> Well it's the character, isn't it? Different character.
<B> Only I was going to smoke a pipe.
<A> No, don't.
<B> Why not?
<A> Well we're gonna need two pipes then, aren't we?
""",
]
